/*
 * This file was generated by the Gradle 'init' task.
 */
pluginManagement {
    repositories {
        mavenLocal()
        maven {
            url = uri("https://papermc.io/repo/repository/maven-public/")
        }
        gradlePluginPortal()
    }
}
rootProject.name = "decaliumclans"
include("test")
