name: DecaliumClans
version: ${version}
main: org.gepron1x.clans.DecaliumClans
api-version: 1.16
authors: [ objectwebasm ]
description: another try.
softdepend: [ PlaceholderAPI ]
depend: [ WorldGuard ]
