site_name: Decalium Clans
theme:
  name: material
  logo: 'kristall.png'
  favicon: 'kristall.png'
  palette:
    scheme: slate
    primary: black
nav:
    - 'index.md'
    - 'Installation.md'
    - 'Creating your first clan.md'
    - 'Member Managment.md'
    - 'Roles.md'
    - 'Homes.md'
    - 'Wars.md'
    - 'Chat.md'
    - 'Messages.md'
    - 'PlaceholderAPI Placeholders.md'
    - 'Permissions.md'
markdown_extensions:
  - tables
